# Model search

Goal:
Test stronger classification models using cross-validation on the training data only.

We will compare:
- Logistic Regression
- Logistic Regression with class_weight="balanced"
- Random Forest
- Extra Trees
- Gradient Boosting
- HistGradientBoosting
- SVC with RBF kernel

The final X_test set is not used during model selection.

In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

print("Current working directory:", Path.cwd())
print("Project root:", PROJECT_ROOT)

Current working directory: c:\temp\python_learning\ml_projects\diabetes_predictions\notebooks
Project root: c:\temp\python_learning\ml_projects\diabetes_predictions

In [4]:
import numpy as np
import pandas as pd

from sklearn.model_selection import StratifiedKFold, cross_validate

from sklearn.metrics import make_scorer, precision_score, recall_score, f1_score

from sklearn.preprocessing import FunctionTransformer, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import (
    RandomForestClassifier,
    ExtraTreesClassifier,
    GradientBoostingClassifier,
    HistGradientBoostingClassifier,
)
from sklearn.svm import SVC

from src.data_utils import load_data, split_features_target, make_train_test_split
from src.preprocessing import replace_suspicious_zeros_with_indicators

from src.evaluation import make_stratified_cv, get_classification_scoring

cv = make_stratified_cv()
scoring = get_classification_scoring()

print(cv)
print(scoring.keys())

StratifiedKFold(n_splits=5, random_state=42, shuffle=True)
dict_keys(['accuracy', 'precision', 'recall', 'f1', 'roc_auc'])

In [5]:
DATA_PATH = PROJECT_ROOT / "data" / "raw" / "diabetes.csv"

df = load_data(DATA_PATH)
X, y = split_features_target(df)
X_train, X_test, y_train, y_test = make_train_test_split(X, y)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

print("\nTrain target distribution:")
print(y_train.value_counts(normalize=True))

print("\nTest target distribution:")
print(y_test.value_counts(normalize=True))

X_train shape: (614, 8)
X_test shape: (154, 8)

Train target distribution:
Outcome
0    0.651466
1    0.348534
Name: proportion, dtype: float64

Test target distribution:
Outcome
0    0.649351
1    0.350649
Name: proportion, dtype: float64

In [6]:
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42,
)

scoring = {
    "accuracy": "accuracy",
    "precision": make_scorer(precision_score, zero_division=0),
    "recall": make_scorer(recall_score, zero_division=0),
    "f1": make_scorer(f1_score, zero_division=0),
    "roc_auc": "roc_auc",
}

In [7]:
from src.pipelines import build_classification_pipeline

In [11]:
from sklearn.linear_model import LogisticRegression
from src.pipelines import build_classification_pipeline

test_pipeline = build_classification_pipeline(
    model=LogisticRegression(max_iter=1000),
    use_scaler=True,
    use_indicators=True,
)

test_pipeline

Pipeline(steps=[('zero_handler',
                 FunctionTransformer(func=<function replace_suspicious_zeros_with_indicators at 0x0000020777F314E0>)),
                ('imputer', SimpleImputer(strategy='median')),
                ('scaler', StandardScaler()),
                ('model', LogisticRegression(max_iter=1000))])

In [12]:
model_configs = {
    "logreg": {
        "model": LogisticRegression(max_iter=1000),
        "use_scaler": True,
    },
    "logreg_balanced": {
        "model": LogisticRegression(max_iter=1000, class_weight="balanced"),
        "use_scaler": True,
    },
    "random_forest": {
        "model": RandomForestClassifier(
            n_estimators=300,
            random_state=42,
            n_jobs=-1,
        ),
        "use_scaler": False,
    },
    "extra_trees": {
        "model": ExtraTreesClassifier(
            n_estimators=300,
            random_state=42,
            n_jobs=-1,
        ),
        "use_scaler": False,
    },
    "gradient_boosting": {
        "model": GradientBoostingClassifier(random_state=42),
        "use_scaler": False,
    },
    "hist_gradient_boosting": {
        "model": HistGradientBoostingClassifier(random_state=42),
        "use_scaler": False,
    },
    "svc_rbf": {
        "model": SVC(
            kernel="rbf",
            probability=True,
            random_state=42,
        ),
        "use_scaler": True,
    },
}

In [13]:
model_search_results = []

for model_name, config in model_configs.items():
    pipeline = build_classification_pipeline(
        model=config["model"],
        use_scaler=config["use_scaler"],
        use_indicators=True,
    )

    cv_results = cross_validate(
        pipeline,
        X_train,
        y_train,
        cv=cv,
        scoring=scoring,
        return_train_score=False,
    )

    model_search_results.append(
        {
            "model": model_name,
            "accuracy_mean": cv_results["test_accuracy"].mean(),
            "accuracy_std": cv_results["test_accuracy"].std(),
            "precision_mean": cv_results["test_precision"].mean(),
            "recall_mean": cv_results["test_recall"].mean(),
            "f1_mean": cv_results["test_f1"].mean(),
            "roc_auc_mean": cv_results["test_roc_auc"].mean(),
        }
    )

model_search_results_df = pd.DataFrame(model_search_results)
model_search_results_df.sort_values("f1_mean", ascending=False)

,model,accuracy_mean,accuracy_std,precision_mean,recall_mean,f1_mean,roc_auc_mean
1,logreg_balanced,0.763841,0.005200,0.645921,0.724474,0.680645,0.844114
0,logreg,0.789871,0.014476,0.760518,0.588815,0.661436,0.843462
2,random_forest,0.762202,0.015949,0.694805,0.579513,0.629656,0.817488
4,gradient_boosting,0.752392,0.024998,0.666820,0.598007,0.627151,0.823158
6,svc_rbf,0.768746,0.007815,0.718920,0.560908,0.626348,0.829581
5,hist_gradient_boosting,0.750833,0.030089,0.666061,0.584275,0.620794,0.800386
3,extra_trees,0.755738,0.022622,0.686448,0.561019,0.615593,0.826946

In [14]:
model_search_results_df.sort_values("recall_mean", ascending=False)

,model,accuracy_mean,accuracy_std,precision_mean,recall_mean,f1_mean,roc_auc_mean
1,logreg_balanced,0.763841,0.005200,0.645921,0.724474,0.680645,0.844114
4,gradient_boosting,0.752392,0.024998,0.666820,0.598007,0.627151,0.823158
0,logreg,0.789871,0.014476,0.760518,0.588815,0.661436,0.843462
5,hist_gradient_boosting,0.750833,0.030089,0.666061,0.584275,0.620794,0.800386
2,random_forest,0.762202,0.015949,0.694805,0.579513,0.629656,0.817488
3,extra_trees,0.755738,0.022622,0.686448,0.561019,0.615593,0.826946
6,svc_rbf,0.768746,0.007815,0.718920,0.560908,0.626348,0.829581